import type {
  AIInsight,
  Delivery,
  Notification,
  Order,
  Produce,
  TrustProfile,
  User,
} from "./types";

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const users: User[] = [
  {
    id: "u-farmer-1",
    name: "Abdul Farms",
    role: "farmer",
    location: "Kano, Nigeria",
    coords: { lat: 12.0022, lng: 8.5919 },
    joined: daysAgo(420),
    avatarInitials: "AF",
    bio: "Family-run 14-hectare farm growing tomatoes, maize and cassava for northern markets.",
    phone: "+234 803 000 1122",
  },
  {
    id: "u-farmer-2",
    name: "Greenvale Cooperative",
    role: "farmer",
    location: "Jos, Nigeria",
    coords: { lat: 9.8965, lng: 8.8583 },
    joined: daysAgo(300),
    avatarInitials: "GC",
    bio: "A 40-member cooperative specialising in highland vegetables and legumes.",
    phone: "+234 806 221 9080",
  },
  {
    id: "u-farmer-3",
    name: "Oyelaran Agro",
    role: "farmer",
    location: "Ibadan, Nigeria",
    coords: { lat: 7.3775, lng: 3.947 },
    joined: daysAgo(120),
    avatarInitials: "OA",
    bio: "Cassava and plantain grower supplying processors across the south-west.",
    phone: "+234 812 445 7781",
  },
  {
    id: "u-buyer-1",
    name: "FreshMart Retail",
    role: "buyer",
    location: "Lagos, Nigeria",
    coords: { lat: 6.5244, lng: 3.3792 },
    joined: daysAgo(380),
    avatarInitials: "FM",
    bio: "Grocery chain with 12 stores sourcing fresh produce weekly.",
    phone: "+234 701 998 3311",
  },
  {
    id: "u-buyer-2",
    name: "Sahel Foods Processing",
    role: "buyer",
    location: "Abuja, Nigeria",
    coords: { lat: 9.0765, lng: 7.3986 },
    joined: daysAgo(210),
    avatarInitials: "SF",
    bio: "Food processor buying grains and tubers in bulk.",
    phone: "+234 705 664 2010",
  },
  {
    id: "u-transporter-1",
    name: "SwiftHaul Logistics",
    role: "transporter",
    location: "Abuja, Nigeria",
    coords: { lat: 9.0579, lng: 7.4951 },
    joined: daysAgo(340),
    avatarInitials: "SH",
    bio: "Cold-chain and dry haulage fleet of 9 trucks covering the north-central corridor.",
    phone: "+234 809 112 6644",
  },
  {
    id: "u-transporter-2",
    name: "Kola Movers",
    role: "transporter",
    location: "Ibadan, Nigeria",
    coords: { lat: 7.4, lng: 3.91 },
    joined: daysAgo(90),
    avatarInitials: "KM",
    bio: "Regional last-mile transporter for perishable produce.",
    phone: "+234 810 553 2298",
    flagged: true,
  },
  {
    id: "u-admin-1",
    name: "Agrolink Operations",
    role: "admin",
    location: "Lagos, Nigeria",
    coords: { lat: 6.4654, lng: 3.4064 },
    joined: daysAgo(500),
    avatarInitials: "AO",
    bio: "Marketplace integrity and operations team.",
    phone: "+234 700 000 0000",
  },
];

export const trustProfiles: TrustProfile[] = [
  {
    userId: "u-farmer-1",
    score: 92,
    level: "High Trust",
    rating: 4.8,
    completedTransactions: 48,
    fulfilmentRate: 97,
    successfulDeliveries: 46,
    cancelledOrders: 2,
    cancellationRate: 4,
    verified: true,
    history: [
      { date: daysAgo(90), score: 84, reason: "Identity verified" },
      { date: daysAgo(45), score: 88, reason: "12 consecutive fulfilled orders" },
      { date: daysAgo(7), score: 92, reason: "5-star rating from FreshMart Retail" },
    ],
  },
  {
    userId: "u-farmer-2",
    score: 81,
    level: "Trusted",
    rating: 4.4,
    completedTransactions: 27,
    fulfilmentRate: 91,
    successfulDeliveries: 25,
    cancelledOrders: 3,
    cancellationRate: 10,
    verified: true,
    history: [
      { date: daysAgo(120), score: 70, reason: "Cooperative onboarded" },
      { date: daysAgo(20), score: 81, reason: "Consistent on-time harvest handover" },
    ],
  },
  {
    userId: "u-farmer-3",
    score: 64,
    level: "Building Trust",
    rating: 3.9,
    completedTransactions: 9,
    fulfilmentRate: 82,
    successfulDeliveries: 8,
    cancelledOrders: 2,
    cancellationRate: 18,
    verified: false,
    history: [
      { date: daysAgo(60), score: 55, reason: "First 3 orders completed" },
      { date: daysAgo(14), score: 64, reason: "Improved fulfilment rate" },
    ],
  },
  {
    userId: "u-buyer-1",
    score: 88,
    level: "High Trust",
    rating: 4.7,
    completedTransactions: 63,
    fulfilmentRate: 95,
    successfulDeliveries: 60,
    cancelledOrders: 3,
    cancellationRate: 5,
    verified: true,
    history: [
      { date: daysAgo(150), score: 79, reason: "Business identity verified" },
      { date: daysAgo(30), score: 88, reason: "Prompt payment streak" },
    ],
  },
  {
    userId: "u-buyer-2",
    score: 76,
    level: "Trusted",
    rating: 4.2,
    completedTransactions: 31,
    fulfilmentRate: 90,
    successfulDeliveries: 28,
    cancelledOrders: 4,
    cancellationRate: 11,
    verified: true,
    history: [{ date: daysAgo(40), score: 76, reason: "Bulk contracts fulfilled" }],
  },
  {
    userId: "u-transporter-1",
    score: 95,
    level: "High Trust",
    rating: 4.9,
    completedTransactions: 128,
    fulfilmentRate: 99,
    successfulDeliveries: 126,
    cancelledOrders: 1,
    cancellationRate: 1,
    verified: true,
    history: [
      { date: daysAgo(200), score: 87, reason: "Fleet documents verified" },
      { date: daysAgo(10), score: 95, reason: "40 deliveries without incident" },
    ],
  },
  {
    userId: "u-transporter-2",
    score: 58,
    level: "Building Trust",
    rating: 3.6,
    completedTransactions: 14,
    fulfilmentRate: 78,
    successfulDeliveries: 11,
    cancelledOrders: 3,
    cancellationRate: 21,
    verified: false,
    history: [
      { date: daysAgo(30), score: 62, reason: "Onboarding completed" },
      { date: daysAgo(5), score: 58, reason: "2 late deliveries flagged" },
    ],
  },
  {
    userId: "u-admin-1",
    score: 100,
    level: "High Trust",
    rating: 5,
    completedTransactions: 0,
    fulfilmentRate: 100,
    successfulDeliveries: 0,
    cancelledOrders: 0,
    cancellationRate: 0,
    verified: true,
    history: [],
  },
];

export const produce: Produce[] = [
  {
    id: "p-1",
    farmerId: "u-farmer-1",
    name: "Roma Tomatoes",
    category: "Vegetables",
    quantityKg: 1200,
    pricePerKg: 850,
    location: "Kano, Nigeria",
    image: "/images/tomatoes.jpg",
    available: true,
    listedAt: daysAgo(5),
    description: "Firm, deep-red Roma tomatoes harvested this week and graded for retail.",
  },
  {
    id: "p-2",
    farmerId: "u-farmer-1",
    name: "Yellow Maize",
    category: "Grains",
    quantityKg: 4000,
    pricePerKg: 520,
    location: "Kano, Nigeria",
    image: "/images/maize.jpg",
    available: true,
    listedAt: daysAgo(12),
    description: "Dried yellow maize at 13% moisture, bagged in 50kg sacks.",
  },
  {
    id: "p-3",
    farmerId: "u-farmer-1",
    name: "Fresh Cassava",
    category: "Tubers",
    quantityKg: 2500,
    pricePerKg: 310,
    location: "Kano, Nigeria",
    image: "/images/cassava.jpg",
    available: true,
    listedAt: daysAgo(2),
    description: "Freshly uprooted cassava tubers, best processed within 48 hours.",
  },
  {
    id: "p-4",
    farmerId: "u-farmer-2",
    name: "Green Peppers",
    category: "Vegetables",
    quantityKg: 600,
    pricePerKg: 1100,
    location: "Jos, Nigeria",
    image: "/images/peppers.jpg",
    available: true,
    listedAt: daysAgo(3),
    description: "Highland-grown green bell peppers, cool-stored after harvest.",
  },
  {
    id: "p-5",
    farmerId: "u-farmer-2",
    name: "Irish Potatoes",
    category: "Tubers",
    quantityKg: 3000,
    pricePerKg: 640,
    location: "Jos, Nigeria",
    image: "/images/potatoes.jpg",
    available: true,
    listedAt: daysAgo(8),
    description: "Table-grade Irish potatoes sorted into medium and large sizes.",
  },
  {
    id: "p-6",
    farmerId: "u-farmer-2",
    name: "Cowpea Beans",
    category: "Legumes",
    quantityKg: 1800,
    pricePerKg: 980,
    location: "Jos, Nigeria",
    image: "/images/beans.jpg",
    available: true,
    listedAt: daysAgo(15),
    description: "Cleaned brown cowpea, hand-sorted with less than 1% foreign matter.",
  },
  {
    id: "p-7",
    farmerId: "u-farmer-3",
    name: "Ripe Plantain",
    category: "Fruits",
    quantityKg: 900,
    pricePerKg: 720,
    location: "Ibadan, Nigeria",
    image: "/images/plantain.jpg",
    available: true,
    listedAt: daysAgo(1),
    description: "Ripe plantain bunches ready for retail or processing.",
  },
  {
    id: "p-8",
    farmerId: "u-farmer-3",
    name: "White Yam",
    category: "Tubers",
    quantityKg: 1500,
    pricePerKg: 890,
    location: "Ibadan, Nigeria",
    image: "/images/yam.jpg",
    available: false,
    listedAt: daysAgo(22),
    description: "Large white yam tubers. Currently reserved — restocking next week.",
  },
];

export const orders: Order[] = [
  {
    id: "o-1",
    produceId: "p-1",
    buyerId: "u-buyer-1",
    farmerId: "u-farmer-1",
    quantityKg: 300,
    totalPrice: 255_000,
    status: "In Transit",
    createdAt: daysAgo(3),
    deliveryId: "d-1",
  },
  {
    id: "o-2",
    produceId: "p-2",
    buyerId: "u-buyer-2",
    farmerId: "u-farmer-1",
    quantityKg: 1000,
    totalPrice: 520_000,
    status: "Awaiting Pickup",
    createdAt: daysAgo(2),
    deliveryId: "d-2",
  },
  {
    id: "o-3",
    produceId: "p-5",
    buyerId: "u-buyer-1",
    farmerId: "u-farmer-2",
    quantityKg: 500,
    totalPrice: 320_000,
    status: "Pending",
    createdAt: daysAgo(1),
    deliveryId: "d-3",
  },
  {
    id: "o-4",
    produceId: "p-6",
    buyerId: "u-buyer-2",
    farmerId: "u-farmer-2",
    quantityKg: 400,
    totalPrice: 392_000,
    status: "Completed",
    createdAt: daysAgo(18),
    ratedByBuyer: true,
    ratedByFarmer: true,
  },
  {
    id: "o-5",
    produceId: "p-3",
    buyerId: "u-buyer-1",
    farmerId: "u-farmer-1",
    quantityKg: 800,
    totalPrice: 248_000,
    status: "Completed",
    createdAt: daysAgo(26),
    ratedByBuyer: true,
    ratedByFarmer: true,
  },
];

export const deliveries: Delivery[] = [
  {
    id: "d-1",
    orderId: "o-1",
    transporterId: "u-transporter-1",
    pickup: { label: "Abdul Farms, Kano", lat: 12.0022, lng: 8.5919 },
    destination: { label: "FreshMart DC, Lagos", lat: 6.5244, lng: 3.3792 },
    distanceKm: 1024,
    fee: 185_000,
    urgency: "Urgent",
    status: "In Transit",
    createdAt: daysAgo(3),
  },
  {
    id: "d-2",
    orderId: "o-2",
    pickup: { label: "Abdul Farms, Kano", lat: 12.0022, lng: 8.5919 },
    destination: { label: "Sahel Foods Plant, Abuja", lat: 9.0765, lng: 7.3986 },
    distanceKm: 432,
    fee: 96_000,
    urgency: "Standard",
    status: "Pending",
    createdAt: daysAgo(2),
  },
  {
    id: "d-3",
    orderId: "o-3",
    pickup: { label: "Greenvale Cooperative, Jos", lat: 9.8965, lng: 8.8583 },
    destination: { label: "FreshMart DC, Lagos", lat: 6.5244, lng: 3.3792 },
    distanceKm: 812,
    fee: 142_000,
    urgency: "Urgent",
    status: "Pending",
    createdAt: daysAgo(1),
  },
];

export const notifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-farmer-1",
    title: "New order received",
    body: "Sahel Foods Processing ordered 1,000kg of Yellow Maize.",
    createdAt: daysAgo(2),
    read: false,
    tone: "success",
  },
  {
    id: "n-2",
    userId: "u-farmer-1",
    title: "AI recommends a price review",
    body: "Your Roma Tomatoes have been listed for 5 days — consider a 5–8% adjustment.",
    createdAt: daysAgo(1),
    read: false,
    tone: "warning",
  },
  {
    id: "n-3",
    userId: "u-buyer-1",
    title: "Your delivery has been accepted",
    body: "SwiftHaul Logistics accepted delivery for order o-1.",
    createdAt: daysAgo(3),
    read: false,
    tone: "info",
  },
  {
    id: "n-4",
    userId: "u-transporter-1",
    title: "New delivery job available",
    body: "Kano → Abuja, 432km, ₦96,000 payout.",
    createdAt: daysAgo(2),
    read: false,
    tone: "info",
  },
  {
    id: "n-5",
    userId: "u-transporter-1",
    title: "Your trust score increased to 95",
    body: "40 deliveries completed without incident.",
    createdAt: daysAgo(10),
    read: true,
    tone: "success",
  },
  {
    id: "n-6",
    userId: "u-admin-1",
    title: "Flagged activity",
    body: "Kola Movers has 2 late deliveries in the last 7 days.",
    createdAt: daysAgo(5),
    read: false,
    tone: "warning",
  },
];

export const insights: AIInsight[] = [
  {
    id: "ai-1",
    role: "farmer",
    question: "What should I do with my tomatoes that have been listed for 5 days?",
    answer:
      "Your Roma Tomatoes have been listed 5 days — 2 days longer than comparable tomato listings in Kano, which clear in about 3 days at ₦780–₦820/kg.",
    suggestion: "Reduce the price by 5–8% (to about ₦790/kg) or enable a bundled delivery option.",
    action: { label: "Review listing", to: "/dashboard/farmer" },
  },
  {
    id: "ai-2",
    role: "buyer",
    question: "Which farmer should I consider?",
    answer:
      "Abdul Farms has the highest trust score among available tomato suppliers (92) and has completed 48 transactions with a 97% fulfilment rate.",
    suggestion: "Order from Abdul Farms and request urgent delivery to hit your weekend restock.",
    action: { label: "Open marketplace", to: "/marketplace" },
  },
  {
    id: "ai-3",
    role: "transporter",
    question: "Which delivery should I prioritize?",
    answer:
      "The Greenvale → FreshMart Lagos job is marked urgent, pays ₦142,000 over 812km, and both parties are high-trust counterparties.",
    suggestion: "Accept the urgent Jos → Lagos job before the standard Kano → Abuja job.",
    action: { label: "See delivery jobs", to: "/dashboard/transporter" },
  },
];
