/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as DashboardFarmerRouteImport } from './routes/dashboard.farmer'
import { Route as DashboardTransporterRouteImport } from './routes/dashboard.transporter'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceProduceIdRouteImport } from './routes/marketplace.$produceId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFarmerRoute = DashboardFarmerRouteImport.update({
  id: '/dashboard/farmer',
  path: '/dashboard/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransporterRoute = DashboardTransporterRouteImport.update({
  id: '/dashboard/transporter',
  path: '/dashboard/transporter',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProduceIdRoute = MarketplaceProduceIdRouteImport.update({
  id: '/marketplace/$produceId',
  path: '/marketplace/$produceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/transporter': typeof DashboardTransporterRoute
  '/marketplace/$produceId': typeof MarketplaceProduceIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/transporter': typeof DashboardTransporterRoute
  '/marketplace/$produceId': typeof MarketplaceProduceIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/transporter': typeof DashboardTransporterRoute
  '/marketplace/$produceId': typeof MarketplaceProduceIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/insights'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/dashboard/transporter'
    | '/marketplace/$produceId'
    | '/profile/$userId'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/insights'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/dashboard/transporter'
    | '/marketplace/$produceId'
    | '/profile/$userId'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/insights'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/dashboard/transporter'
    | '/marketplace/$produceId'
    | '/profile/$userId'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  InsightsRoute: typeof InsightsRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardFarmerRoute: typeof DashboardFarmerRoute
  DashboardTransporterRoute: typeof DashboardTransporterRoute
  MarketplaceProduceIdRoute: typeof MarketplaceProduceIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/farmer': {
      id: '/dashboard/farmer'
      path: '/dashboard/farmer'
      fullPath: '/dashboard/farmer'
      preLoaderRoute: typeof DashboardFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transporter': {
      id: '/dashboard/transporter'
      path: '/dashboard/transporter'
      fullPath: '/dashboard/transporter'
      preLoaderRoute: typeof DashboardTransporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$produceId': {
      id: '/marketplace/$produceId'
      path: '/marketplace/$produceId'
      fullPath: '/marketplace/$produceId'
      preLoaderRoute: typeof MarketplaceProduceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  InsightsRoute: InsightsRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardFarmerRoute: DashboardFarmerRoute,
  DashboardTransporterRoute: DashboardTransporterRoute,
  MarketplaceProduceIdRoute: MarketplaceProduceIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
